### ISSUE TITLE
Successful site builds trigger their own rolling deployment

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Sprints#105]

**Comment by richarddubay** [comment]
[  ] Kubernetes is implemented and port requirements are understood so multiple instances can run together.
[  ] CircleCI runs EE-core and deploys it to AWS.

**Comment by delianides** [comment]
Multiple Instances can run together and a successful build of a site triggers its own rolling deployment.

**Comment by dcs619** [comment]
QA'd with @delianides
