### ISSUE TITLE
Support IT domain name setup

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Sprints#106]

**Comment by richarddubay** [comment]
Things IT will be doing:
[  ] Send updates to all people currently using rock.newspring.cc to make them aware of the change.
[  ] rock.newspring.cc is moved to rockstaging.newspring.cc
[  ] Remove rock.newspring.cc DNS entries
[  ] rockstaging.newspring.cc uses SSL
[  ] rockbeta.newspring.cc uses SSL

**Comment by dcs619** [comment]
staging-rock is set to track github/newspring/Rock-Plugins/develop
beta-rock is set to track github/newspring/Rock-Plugins/release

**Comment by dcs619** [comment]
Moving to Done since this entire Azure set up is getting blown away.
