### ISSUE TITLE
Create DB volume Docker container w/existing mySQL data

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Sprints#115]

**Comment by richarddubay** [comment]
We need a local Docker container that mimics production
[  ] DB instance works within Docker
[  ] Ability to import DB to a Docker instance from Norma
[  ] Able to run EE sites locally within Docker

**Comment by delianides** [comment]
I can meet all three of the acceptance criteria but having a DB container that already has data inside is proving difficult. Right now the best (easiest) solution is to have a sql dump imported when the container is started.
