### ISSUE TITLE
Layout "Ask Pastor P" page

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Sprints#121]
- Landing page where people can submit a question should live within the NS site framework
- Facebook comment function included on page
- Should be linked from the NewSpring Sex sermon page
- Should link to NewSpring Sex sermon page
- Access should be given to the marketing team to view and export questions

**Comment by briankalwat** [comment]
- Landing page where people can submit a question should live within the NS site framework
- Facebook comment function included on page
- Should be linked from the NewSpring Sex sermon page
- Should link to NewSpring Sex sermon page
- Access should be given to the marketing team to view and export questions

**Comment by richarddubay** [comment]
This is waiting for branding from the sex series, right @briankalwat? Will there even be a series page on NewSpring to link from/to? Because it is supposed to link both ways.

**Comment by briankalwat** [comment]
@richarddubay there will be once we have the branding/hero.
