### ISSUE TITLE
Integrating Facebook comments for "Ask Pastor P" page

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Sprints#123]
- Landing page where people can submit a question should live within the NS site framework
- Facebook comment function included on page
- Should be linked from the NewSpring Sex sermon page
- Should link to NewSpring Sex sermon page
- Access should be given to the marketing team to view and export questions

**Comment by briankalwat** [comment]
@jonhorton @richarddubay this is functioning within the page, but still not sending comments to Facebook itself. I personally don't see the value in having them on the page if it doesn't post to people's news feeds, but that's just my opinion.

**Comment by jonhorton** [comment]
Thanks @briankalwat! We're going to go ahead and leave this on the page since comments themselves are functioning. We'll add a bug as a separate card for next sprint to resolve that issue. cc: @richarddubay

**Comment by richarddubay** [comment]
This is on the page and a bug has been added. Moving to done.
