### ISSUE TITLE
Documentation for dynamic content creation (Blocks)

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Sprints#13]
Style guide of what content units look like, how to create one, etc.

**Comment by dcs619** [comment]
Completion Criteria:
[] Document usage and procedures for all existing asset types
[] Document usage and procedures for new/suggested asset types

**Comment by edolyne** [comment]
@dcs619 based on our audience for this I documented everything on newspring.io, we will probably need to allow for user feedback as it's used so that we can make changes if needed.

**Comment by dcs619** [comment]
Requested Bron to review.

**Comment by dcs619** [comment]
I looked over this section & some of the things were new to me. I'm sure I will have questions while working in & through these things, but I will let you know. 

Thanks - Bron
