### ISSUE TITLE
Annual Report changes

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Sprints#136]
All pages
Can you adjust the font sizes on the numbers to better align with the 2013 Annual report? Most of the numbers in the 2014 report are all the same size and the 2013 had varying sizes that made it look better. 

You Can't Do Life Alone
Under "Overwhelmed Groups" in the first sentence should the period at the end of the sentence be inside or outside of the quotations around Overwhelmed? I was thinking it should be outside, but grammar isn't my strength. 

You Can't Outgive God
on the third row can we add "Articles of clothing given / 13,600"
Added, but this throws off the balance of the page

KidSpring
Under "KidSpring Resources for Churches" can we check to see if that 16,783 number is current? If you guys don't have an updated number for that just remove the last sentence. 

Can we get "KidSpring Vision & Mission" and "KidSpring Resources for Churches" more centered on the page since we had to delete the number of resources downloaded.

NewSpring Network
on the bottom row "Kenya and Uganda" lets add a link to the NewSpring Missions page
for 3D church - can we change the copy on the second sentence to be "3D launched their second location in Tallinn. They are the first church in Estonia to go multisite."

NewSpring Website and App
on the bottom row can we shift the second two stats to the left so there isn't a big gap after "Average Daily Site visits" and get "Average Weekly Devices Connected to Live Services" on to one line

**Comment by briankalwat** [comment]
"Can we check to see if that 16,783 number is current?" - I'm not sure how to check this number.

**Comment by richarddubay** [comment]
1. Second paragraph in intro: "...we're seeing in happen in our church." should be "...we're seeing happen in our church."

2. You Can't Do Life Alone. 

Under "Overwhelmed Groups Stories"

"...take a first steps to start praying..." should be "...take a first step to start praying..."

Also, is this a quote from someone? Should it be displayed as a quote?

3. NewSpring Network
"Serving Other Churches" is really hard to read in that blue.
Why does it say "TWO TRIPS"? Why not just use the number 2?

4. Website & App
Maybe it's just me or my screen, but the footnotes on the last two items at the bottom of the page are kind of hard to read in gray.

**Comment by richarddubay** [comment]
Comment to see if this issue will show back up in waffle.
