### ISSUE TITLE
Double-check attendance code changes on subsequent check-in

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Sprints#145]

**Comment by richarddubay** [comment]
https://github.com/NewSpring/Rock-Plugins/issues/95

**Comment by dcs619** [comment]
Set a breakpoint inside save attendance and see if the code changes for the same person

**Comment by benwiley** [comment]
It changes -  I watched it change 3 times for Cullen for Wonder Way 7 for 4:30 (test) service
