### ISSUE TITLE
Document existing UI promo elements on the web

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Sprints#24]
Completion Criteria:
[] Current possibilities defined with asset types needed
[] Design showcase of current hero types using previous campaigns

**Comment by dcs619** [comment]
Elements should match existing brand standards and be evaluated by the team.

**Comment by dcs619** [comment]
Document the custom experiences currently available on newspring.cc (heroes, videos, etc)

How do I showcase this new series on the web?
What kind of assets do I have available?
I have a series video, how can I display that online?

**Comment by richarddubay** [comment]
Documentation has been uploaded to https://newspring.io/docs/reference/current-ui-hero-types
