### ISSUE TITLE
Make suggestions for a future style guide

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Sprints#50]
Suggestion of what our style guide should be

**Comment by dcs619** [comment]
@edolyne @joelthereid joint project

**Comment by briankalwat** [comment]
@dcs619 what would the deliverables for this be?

**Comment by briankalwat** [comment]
https://docs.google.com/a/newspring.cc/document/d/1CA0TvXGI7j1OG336obGWLjgvU4gXLqjqthZ5zgxEdrA/edit#
