### ISSUE TITLE
/Apps page design

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Sprints#6]
Completion Criteria:
[] All supported platforms are highlighted in a clear way
[] All apps are linked to the various store(s)
[] Current sections of the app are explained
[] Designed mobile first, should be easy to download without having to read everything
[] Matches print/video/other ads and promotions

**Comment by dcs619** [comment]
Part of a larger rewrite/product page for NewSpring Apps

**Comment by JoeltheReid** [comment]
We'll need to have a Design Review meeting for this. :)
