### ISSUE TITLE
Research How to Customize User's Rock Page

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Sprints#62]
Document in Hackpad

**Comment by briankalwat** [comment]
Joint task w/@mdrouse.

**Comment by richarddubay** [comment]
[  ] Research other blocks to view workflows
[  ] Research a way to add a list of follow-up assignments
[  ] Research Group Security Roles to configure a standard dashboard per Security Group (Finance, Guest Services, Volunteer, Staff, etc.)
