### ISSUE TITLE
Move HTML Markup in Fieldgroup templates to Layouts/Partials

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Sprints#79]

**Comment by edolyne** [comment]
[x] editorial-entry
[x] editorial-list
[x] sermons-collection
[x] sermons-entry
[x] sermons-list
[] studies-collection
[] studies-entry
[x] studies-list

**Comment by briankalwat** [comment]
@edolyne 
- editorial_list/sermons_list/studies_list: Have you attempted abstracting pagination as an element or section?
