### ISSUE TITLE
Implement Mocha Casper Testing

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Sprints#90]

**Comment by richarddubay** [comment]
Completion Criteria:

[ ] Create a norma-mocha-casperjs package to use in place of our current norma-casperjs package for better overall test coverage and prettier results in the terminal.

[ ] Publish said package to NPM.

[ ] Update the projects that currently use the norma-casperjs package to use the new package and refactor their tests to work correctly with mocha-casperjs.

**Comment by richarddubay** [comment]
The norma-mocha-casperjs package has been created and is on Github.

**Comment by dcs619** [comment]
Published to NPM: https://www.npmjs.com/package/norma-mocha-casperjs
