### ISSUE TITLE
Setup API endpoints and hooks on Apollos

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Sprints#97]

**Comment by richarddubay** [comment]
Completion Criteria
[  ] Creating of person collection (with schema matching Rock) in Apollo
[  ] Linking of account creation to people creation (on Apollos)
[  ] CUD updates on people data from Rock -> Apollos
[  ] CRUD updates on people data from Apollos -> Rock
[  ] Write tests for new code

**Comment by jbaxleyiii** [comment]
Reviewed and working great! Fantastic work @benwiley
